spring.application.name=projectUsingSpring

spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=your_database_username
spring.datasource.password=your_database_password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.h2.console.enabled=true

spring.jpa.defer-datasource-initialization=true

#Spring Security
#Custom Login Credentials
spring.security.user.name=your_login_username
spring.security.user.password=your_login_password

