spring.application.name=projectUsingSpring

spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=abcd
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.h2.console.enabled=true

spring.jpa.defer-datasource-initialization=true

#Spring Security
#Custom Login Credentials
spring.security.user.name=techmart
spring.security.user.password=t@1234

